### ISSUE TITLE
Improvement: When attributes clash it may be useful to have the attribute name passed to the callback

### ISSUE THREAD

**Issue by robinj** [hlfshell/controlled-merge#1]
If we need to keep a record of clashing keys, for example, it would be useful to have the attribute name in the callback function.

**Comment by hlfshell** [comment]
OK, that's a pretty sensible fix. I'm travelling for work right now. Will get to this when I get back.

**Comment by robinj** [comment]
Thanks. I have actually submitted a pull request which should implement this behaviour. It is, of course, only one line of code changed. 

Although the current documentation is still valid, I can document the new functionality that comes with this as a separate issue and in a separate pull request. Just trying to avoid forking into a new project unnecessarily because I am writing a gulp plugin which is going to depend on this code. 

I should be able to get the docs done by midday tomorrow (GMT - I'm London based)
